config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  resources :rooms
  post 'rooms/:id/join', to: 'room_users#join', as: 'join_room'
  delete 'rooms/:id/leave', to: 'room_users#leave', as: 'leave_room'
  delete 'rooms/:id/kick', to: 'room_users#kick', as: 'kick_user_room'
  resources :estimations
  resources :estimation_values
  resources :user_stories
  patch 'user_story/:id/restart', to: 'user_stories#restart',as: 'restart_user_story'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_story.rb
class UserStory < ApplicationRecord
  validates :title, presence: true, uniqueness: { scope: %i[room_id] }
  belongs_to :room, dependent: nil, inverse_of: :user_stories

  has_many :estimations, dependent: :destroy
  has_many :estimation_values, through: :estimations, dependent: nil
  has_many :users, through: :estimations, dependent: nil
  belongs_to :estimation_value, optional: true

  def all_users_have_estimated?
    users_in_room = room.users.to_set
    users_in_room.add(room.admin)
    users_with_estimation = estimations.map(&:user).to_set
    users_in_room.difference(users_with_estimation).empty?
  end

  def update_consensus
    return unless all_users_have_estimated?

    minimum_estimation_placement = EstimationValue.joins(:estimations).where('estimations.user_story' => self).minimum(:placement)
    maximum_estimation_placement = EstimationValue.joins(:estimations).where('estimations.user_story' => self).maximum(:placement)
    update(is_estimated: true)

    if maximum_estimation_placement - minimum_estimation_placement <= 1
      update(estimation_value: EstimationValue.find_by(placement: maximum_estimation_placement))
    else
      update(estimation_value: nil)
      ConsensusMailer.with(user_story: self).consensus_failed_email.deliver_later
    end
  end

  def delete_estimations
    estimations.delete_all
  end
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin_status, except: %i[show destroy restart]
  before_action :set_requested_user_story_value, except: %i[create]

  def create
    user_story = UserStory.new(user_story_params)
    room = Room.find(params[:room_id])
    user_story.room = room
    flash_message = if user_story.save
                      { notice: t('views.user_stories.actions.create.success') }
                    else
                      { warning: t('views.user_stories.actions.create.failure') }
                    end
    redirect_to room_path(room), flash_message
  end

  def show
    @estimation_values = EstimationValue.order(placement: :asc)
    @estimation = current_user.estimations.find_or_initialize_by(user_story: @user_story)
    @estimations = @user_story.estimations.all

    if @user_story.room.include?(current_user)
      render 'show'
    else
      redirect_to rooms_path, alert: t('views.user_stories.access.denied')
    end
  end

  def update
    if @user_story.update(user_story_params)
      redirect_to user_story_path, notice: t('views.user_stories.flash_messages.update.success')
    else
      redirect_to user_story_path, alert: t('views.user_storiesflash_messages.update.failure')
    end
  end

  def destroy
    room = @user_story.room
    redirect_to room, alert: t('views.user_stories.access.denied') unless current_user == room.admin
    @user_story.destroy
    redirect_to room, notice: t('views.user_stories.flash_messages.delete.success')
  end

  def restart
    room = @user_story.room
    return redirect_to room, alert: t('views.user_stories.access.denied') unless current_user == room.admin

    if @user_story.estimation_value
      flash_message = { alert: t('views.user_stories.flash_messages.restart.consensus_found') }
    else
      @user_story.delete_estimations
      @user_story.update(is_estimated: false)
      flash_message = { warning: t('views.user_stories.flash_messages.restart.success') }
    end
    redirect_to @user_story, flash_message
  end

  private

  def user_story_params
    params.require(:user_story).permit(%i[title description])
  end

  def authenticate_admin_status
    room = Room.find(params[:room_id])
    redirect_to rooms_path(room), alert: t('views.user_stories.access.denied') unless current_user == room.admin
  end

  def set_requested_user_story_value
    @user_story = UserStory.find(params[:id])
  end
end

app/views/user_stories/_modal.html.erb
<div class="modal fade" id=<%=modalName%> tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel"><%= t('active_record.models.user_story')  %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%=form_with model: user_story do |f| %>
      <div class="modal-body">
          <div class="mb-3">
            <%= f.label :title ,class: "col-form-label", for: "title" %>
            <%= f.text_field :title, class: "form-control", id: "title" %>
          </div>
          <div class="mb-3">
            <%= f.label :description ,class: "col-form-label", for: "message-text" %>
            <%= f.text_area :description, class: "form-control", id: "message-text" %>
          </div>
          <%= hidden_field_tag 'room_id', room_id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t('views.rooms.show.buttons.close')%></button>
          <%= f.submit class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_stories/show.html.erb
<%= render partial: 'modal', locals: { user_story: @user_story, modalName: 'updateModal', room_id: @user_story.room.id} %>
<div class="container-fluid">
  <div class="card <%= @user_story.estimation_value ? 'bg-success' : '' %>" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @user_story.title %></h5>
      <p class="card-text"><%= @user_story.description %></p>
      <ul class="list-group list-group-flush">
        <li class="list-group-item <%= @user_story.estimation_value ? 'bg-success' : '' %>">
          <% if @estimation.new_record? %>
            <%= form_with model: @estimation do |f| %>
              <div class="row align-items-center">
                <%= f.hidden_field :user_story_id, value: @user_story.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <div class="col-auto">
                  <%= f.select :estimation_value_id, @estimation_values.collect { |ev| [ev.value, ev.id] }  %><br/>
                </div>
                <div class="col-auto">
                  <%= f.submit t('views.user_stories.show.buttons.estimate'), class: 'btn btn-info' %>
                </div>
              </div>
            <% end %>
          <% else %>
            <%= t('views.user_stories.show.content.estimation') %> : <%= @estimation.estimation_value.value %>
          <% end %>
        </li>
        <% if @user_story.estimation_value %>
          <li class="list-group-item <%= @user_story.estimation_value ? 'bg-success' : '' %>">
            <%= t('views.user_stories.show.content.final_estimation')%> : <%= @user_story.estimation_value.value %>
          </li>
        <% end %>
        <% if @user_story.room.admin == current_user %>
          <%if @user_story.estimation_value.nil? %>
            <li class="list-group-item <%= @user_story.estimation_value ? 'bg-success' : '' %>">
              <%= link_to t('views.user_stories.show.buttons.restart'), restart_user_story_path(@user_story), method: :patch, data: {confirm: t('views.user_stories.show.confirmations.restart'),}, class: 'btn btn-warning m-1'%>
            </li>
          <% end %>
          <li class="list-group-item <%= @user_story.estimation_value ? 'bg-success' : '' %>">
            <div class="row align-items-center justify-content-between">
              <div class="col-auto">
                <button type="button" class="btn btn-primary m-1" data-bs-toggle="modal" data-bs-target="#updateModal">
                  <%= t('views.user_stories.show.buttons.update') %>
                </button>
              </div>
              <div class="col-auto">
                <%= link_to t('views.user_stories.show.buttons.delete'), user_story_path(@user_story), method: :delete, data: {confirm: t('views.user_stories.show.confirmations.delete'),}, class: 'btn btn-danger m-1'%>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <ul class="list-group my-2" style="width: 18rem;">
    <li class='list-group-item list-group-item-<%= @estimations.find_by(user: @user_story.room.admin) ? :success : :danger %>'>
        <%= @user_story.room.admin.username %>
        <% if @user_story.is_estimated %>
        : <%= @estimations.find_by(user: @user_story.room.admin).estimation_value.value %>
        <% end %>
    </li>
    <% @user_story.room.users.each do |user| %>
      <li class="list-group-item list-group-item-<%= @estimations.find_by(user: user) ? :success : :danger %>" >
        <%= user.username %>
        <% if @user_story.is_estimated %>
        : <%= @estimations.find_by(user: user).estimation_value.value %>
        <% end %>
    </li>
    <% end %>
  </ul>
</div>