config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  resources :rooms
  post 'rooms/:id/join', to: 'room_users#join', as: 'join_room'
  delete 'rooms/:id/leave', to: 'room_users#leave', as: 'leave_room'
  delete 'rooms/:id/kick', to: 'room_users#kick', as: 'kick_user_room'
  resources :estimations
  resources :estimation_values
  resources :user_stories
  patch 'user_story/:id/restart', to: 'user_stories#restart',as: 'restart_user_story'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/estimation_value.rb
class EstimationValue < ApplicationRecord
  default_scope { order(placement: :asc) }

  validates :value, uniqueness: true, presence: true
  validates :placement, uniqueness: true, presence: true

  has_many :estimations, dependent: :destroy
  has_many :users, through: :estimations, dependent: nil
  has_many :user_stories, through: :estimations, dependent: nil
end

app/controllers/estimation_values_controller.rb
class EstimationValuesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin_status
  before_action :set_requested_estimation_value, only: %i[update destroy]

  def index
    @estimation_values = EstimationValue.order(placement: :ASC)
    @estimation_value = EstimationValue.new
  end

  def create
    estimation_value = EstimationValue.new(estimation_values_params)

    if estimation_value.save
      redirect_to estimation_values_path, notice: t('views.estimations.values.flash_messages.create.success')
    else
      redirect_to estimation_values_path, alert: t('views.estimations.values.flash_messages.create.failure')
    end
  end

  def update
    if @estimation_value.update(estimation_values_params)
      redirect_to estimation_values_path, notice: t('views.estimations.values.flash_messages.update.success')
    else
      redirect_to estimation_values_path, alert: t('views.estimations.values.flash_messages.update.failure')
    end
  end

  def destroy
    @estimation_value.destroy
    redirect_to estimation_values_path, notice: t('views.estimations.values.flash_messages.delete.success')
  end

  private

  def estimation_values_params
    params.require(:estimation_value).permit(%i[value placement])
  end

  def set_requested_estimation_value
    @estimation_value = EstimationValue.find(params[:id])
  end

  def authenticate_admin_status
    redirect_to root_path, warning: t('views.estimations.values.flash_messages.access.denied') unless current_user.isAdmin
  end
end

app/views/estimation_values/_create_model.html.erb
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createModalLabel">Estimation value</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @estimation_value, local: true) do |f| %>
          <div class="d-flex-col">
            <%= f.label :value, class: "form-label" %>
            <%= f.number_field :value, class: "form-control" %>
          </div>
          <div class="d-flex-col">
            <%= f.label :placement, class: "form-label" %>
            <%= f.number_field :placement, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit t('views.estimations.values.options.create'), class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/estimation_values/_modal.html.erb
<div class="modal fade" id=<%=modalName%> tabindex="-1" aria-labelledby="#Modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Estimation value</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: estimation_value do |f| %>
          <div class="d-flex-col">
            <%= f.label :value, class: "form-label" %>
            <%= f.number_field :value, class: "form-control" %>
          </div>
          <div class="d-flex-col">
            <%= f.label :placement, class: "form-label" %>
            <%= f.number_field :placement, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit class: "btn btn-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/estimation_values/index.html.erb
<%= render partial: 'modal', locals: { estimation_value: @estimation_value, modalName: 'createModal'} %>
<div class="container">
  <div class="d-flex justify-content-between">
    <h1><%= t('views.estimations.values.title')%> </h1>
    <div>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
        <%= t('views.estimations.values.options.create') %>
      </button>
    </div>
  </div>
  <% if @estimation_values.blank? %>
    <h3> <%= t('views.estimations.values.no_values') %> </h3>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><%= t('active_record.attributes.estimations.values.placement')%></th>
          <th scope="col"><%= t('active_record.attributes.estimations.values.value')%></th>
        </tr>
      </thead>
      <tbody>
        <% @estimation_values.each do |estimation_value| %>
          <tr>
            <td> <%=estimation_value.placement%> </td>
            <td><%= estimation_value.value %></td>
            <td>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateModal<%=estimation_value.id%>">
                <%= t('views.estimations.values.options.update') %>
              </button>
              </td>
              <td><%= link_to t('views.estimations.values.options.delete'), estimation_value_path(estimation_value) ,method: 'delete', type: 'button', class: 'btn btn-danger' %></td>
              <%= render partial: 'modal', locals: { estimation_value: estimation_value, modalName: "updateModal#{estimation_value.id}"} %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>