config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  resources :rooms
  post 'rooms/:id/join', to: 'room_users#join', as: 'join_room'
  delete 'rooms/:id/leave', to: 'room_users#leave', as: 'leave_room'
  delete 'rooms/:id/kick', to: 'room_users#kick', as: 'kick_user_room'
  resources :estimations
  resources :estimation_values
  resources :user_stories
  patch 'user_story/:id/restart', to: 'user_stories#restart',as: 'restart_user_story'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><%= link_to t('views.static_pages.home.title'), home_path, class: "nav-link px-2 link-secondary"%></li>
      <li><%= link_to t('views.static_pages.about.title'), about_path, class: "nav-link px-2 link-secondary"%></li>
      <li><%= link_to t('views.static_pages.help.title'), help_path, class: "nav-link px-2 link-secondary"%></li>
      <li><%= link_to t('views.rooms.index.title'), rooms_path, class: "nav-link px-2 link-secondary"%></li>
    </ul>
    <% if current_user %>
      <div class="col-md-3 text-end">
        <%= link_to t('users.options.edit'), edit_user_registration_path, class: "btn btn-outline-primary me-2", type: "button" %>
        <%= link_to t('users.options.signout'), destroy_user_session_path, method: "delete",  class: "btn btn-outline-primary", type: "button" %>
      </div>
    <% else %>
      <div class="col-md-3 text-end">
        <%= link_to t('users.options.login'), new_user_session_path, class: "btn btn-outline-primary me-2", type: "button" %>
        <%= link_to t('users.options.signup'), new_user_registration_path, class: "btn btn-primary", type: "button" %>
      </div>
    <%end%>
  </header>
</div>