config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  resources :rooms
  post 'rooms/:id/join', to: 'room_users#join', as: 'join_room'
  delete 'rooms/:id/leave', to: 'room_users#leave', as: 'leave_room'
  delete 'rooms/:id/kick', to: 'room_users#kick', as: 'kick_user_room'
  resources :estimations
  resources :estimation_values
  resources :user_stories
  patch 'user_story/:id/restart', to: 'user_stories#restart',as: 'restart_user_story'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id', dependent: nil, inverse_of: :owned_rooms
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users, dependent: nil
  has_many :user_stories, dependent: :destroy, inverse_of: :room

  def include?(user)
    users.include?(user) || admin == user
  end

  def remove_user(user)
    users.destroy(user)
  end

  def add_user(user)
    return if include?(user)

    users << user
  end

  def self.available_filters
    %i[all available included admin]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_requested_room_value, except: %i[index create]

  def index
    @rooms = RoomSearchService.new(params[:search], params[:filter], current_user.id).search
    @categories = Room.available_filters
    @room = Room.new
  end

  def show
    @user_story = UserStory.new
    return if @room.include?(current_user)

    flash[:alert] = 'You need to join the room to see the room!'
    redirect_to rooms_path
  end

  def create
    room = Room.new(room_params)
    room.admin = current_user
    if room.save
      redirect_to room_path(room), notice: t('views.rooms.actions.create_room.success')
    else
      redirect_to rooms_path, alert: t('views.rooms.actions.create_room.failure')
    end
  end

  def update
    if @room.admin == current_user
      if @room.update(room_params)
        redirect_to room_path(@room), notice: t('views.rooms.actions.update_room.success')
      else
        redirect_to room_path(@room), alert: t('views.rooms.actions.update_room.failure')
      end
    elsif @room.users.include?(current_user)
      redirect_to room_path(@room), warning: t('views.rooms.actions.update_room.denied')
    else
      redirect_to rooms_path, warning: t('views.rooms.actions.update_room.denied')
    end
  end

  def destroy
    if @room.admin == current_user
      @room.destroy
      redirect_to rooms_path, notice: t('views.rooms.actions.delete_room.success')
    elsif @room.users.include?(current_user)
      redirect_to room_path(@room), alert: t('views.rooms.actions.delete_room.failure')
    else
      redirect_to rooms_path, alert: t('views.rooms.actions.delete_room.failure')
    end
  end

  private

  def set_requested_room_value
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(%i[name])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
  <%= form_with(model: @room, class: 'form-inline') do |f| %>
  <div class="container-fluid">
    <div class="row">
      <div class='col-2'>
        <%= f.text_field :name, placeholder: 'name', class: "form-control" %>
      </div>
      <div class="col-1">
        <%= f.submit class: "btn btn-warning" %>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class='container-fluid'>
  <h1><%= t('views.rooms.index.title') %></h1>
  <div class="row justify-content-between">
    <div class='col-6'>
      <%= form_with(path: rooms_path, method: 'get', local: true) do %>
        <%= text_field_tag(:search) %>
        <%= select_tag(:filter, options_for_select(@categories))%>
        <%= submit_tag(t('views.rooms.index.buttons.search'), class:'btn btn-secondary')%>
      <% end %>
    </div>
    <div class='col'>
      <%= render partial: 'form'%>
    </div>
  </div>
  <% if @rooms.blank? %>
    <h5><%= t('views.rooms.index.available_rooms.no_rooms') %></h5>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col"><%= t('active_record.attributes.room.name') %></th>
          <th scope="col"><%= t('active_record.attributes.room.admin') %></th>
          <th scope="col"><%= t('views.rooms.index.table.titles.options') %></th>
        </thead>
        <tbody>
          <% @rooms.each do |room| %>
            <tr>
              <th scope="row"><%= room.id %></th>
              <td><%= room.name %></td>
              <td><%= room.admin.username %></td>
              <td>
                <% if room.include?(current_user) %>
                  <%= link_to t('views.rooms.index.buttons.enter'), room_path(room), type: 'button', class: 'btn btn-danger' %>
                <% else %>
                  <%= link_to t('views.rooms.index.buttons.join'), join_room_path(room), method: 'post', type: 'button', class: 'btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

app/views/rooms/show.html.erb
<div class="container-fluid">
    <% if @room.admin == current_user %>
        <%= render partial: 'user_stories/modal', locals: {user_story: @user_story, modalName: 'create_user_story_modal', room_id: @room.id} %>
        <%= render partial: 'form'%>
        <%= link_to t('views.rooms.show.buttons.destroy'), room_path(@room), method: 'delete', type: 'button', class: 'btn btn-danger float-end mx-2'%>
        <button type="button" class="btn btn-success m-3" data-bs-toggle="modal" data-bs-target="#create_user_story_modal" data-bs-whatever="@mdo"><%= t('helpers.submit.user_story.create') %></button>
    <% else %>
      <%= link_to t('views.rooms.show.buttons.leave'), leave_room_path(@room), method: 'delete', type: 'button', class: 'btn btn-danger float-end' %>
    <% end%>
  <% if @room.users.blank? %>
    <h5><%= t('views.rooms.show.other_users.no_users') %></h5>
    <h5><%= t('views.rooms.show.other_users.call_to_action') %></h5>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><%= t('active_record.attributes.user.username') %></th>
          <% if @room.admin == current_user %>
            <th scope="col" class="text-end"><%= t('views.rooms.show.table.titles.kick') %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <td><%= @room.admin.username %></td>
        <% @room.users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td>
              <% if @room.admin == current_user %>
                <%= link_to t('views.rooms.show.table.titles.kick'), kick_user_room_path(@room, user_id: user.id), method: 'delete',type: 'button', class: 'btn btn-danger float-end', data: {confirm: 'Are you sure?'} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <% if @room.user_stories.blank? %>
    <h5><%= t('views.rooms.show.user_stories.no_stories') %></h5>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><%= t('active_record.attributes.user_stories.title') %></th>
        </tr>
      </thead>
      <tbody>
        <% @room.user_stories.each do |user_story| %>
          <tr>
            <td><%= user_story.title %></td>
            <td><%= link_to t('views.rooms.show.buttons.user_story.show'), user_story_path(user_story), type: 'button', class: 'btn btn-success float-end' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>